# Generated by Django 4.0.2 on 2022-02-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyIQ', '0002_remove_question_questions_question_option_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='opt_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='opt_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='opt_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4',
            new_name='opt_4',
        ),
    ]
