# Generated by Django 4.0.2 on 2022-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyIQ', '0003_rename_option_1_question_opt_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
